install:
  - choco install gitversion.portable -pre -y
  
before_build:  
  - .paket\paket.bootstrapper.exe
  - .paket\paket.exe restore
  - ps: gitversion /l console /output buildserver

build:
  project: JsonLd.Entities.sln

configuration: Release

after_build:
  - .paket\paket.exe pack output nugets include-referenced-projects version %GitVersion_NuGetVersion%
  
after_test:
  - .\packages\OpenCover\tools\OpenCover.Console.exe -register:user -target:nunit-console.exe -targetargs:"/nologo /noshadow src\Nancy.RDF.Tests\bin\Release\Nancy.Rdf.Tests.dll" -returntargetcode -filter:"+[Nancy.Rdf]*" -hideskipped:All -output:.\Nancy.Rdf_coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "Nancy.Rdf_coverage.xml"

artifacts:
  - path: 'nugets\*.nupkg'

cache:
  - packages -> paket.lock